module.exports = {
  entry: [
    {
      entry: './package',
      ignore: [
        'mixins',
        'badge',
        'circle',
        'address-picker',
        'action-sheet',
        'button',
        'cell',
        'cell-group',
        'skeleton',
        'checkbox',
        'checkbox-group',
        'collapse-item',
        'collapse',
        'nav-bar',
        'search',
        'rate',
        'radio',
        'radio-group',
        'pull-refreshing',
        'switch',
        'loading',
        'laod-more',
        'input',
        'form',
        'form-item',
        'image',
        'index-bos',
        'index-anchor',
        'swipe-action',
        'tab-bar',
        'tab-bar-item',
        'tabs',
        'tabs-pane',
        'piacker',
        'date-picker',
        'uploader',
        'image-preview',
        'toast',
        'dialog',
      ],
    },
  ],
  mime: ['js', 'vue'],
};
